### ISSUE TITLE
Use scrapy together with warcio

### ISSUE THREAD

**Issue by CuloArdido** [webrecorder/warcio#100]
I am interested in downloading a list of files through [scrapy](https://scrapy.org/) to save them in a warc file, is that possible? The documentation only shows how to do it with the `requests` module and a simple request so if there is any way to do this maybe it could also be added as an example of use in the documentation.

**Comment by wumpus** [comment]
Doesn't scrapy already have warc support? Via plugins. Searching for [scrapy warc] shows several candidates.

**Comment by CuloArdido** [comment]
> Doesn't scrapy already have warc support?

To be honest I had not thought of looking for something like that because as the WARC format is something so "niche" I imagined that warcio was the only Python implementation available.
Following your suggestion I found [this script](https://bitbucket.org/cavorite/scrapy-warc/src/default/scrapywarc.py) that does what I need. I have not had the opportunity to try it but if you want you can give this issue as resolved (if I get to find something better then I will comment on it here).
