### ISSUE TITLE
Using warcio with scrapy - what does the payload need to look like?

### ISSUE THREAD

**Issue by Chris8080** [webrecorder/warcio#101]
Hello,

I'd like to use the warcio library with scrapy and saw the other thread about it as well as the code.
The difference for me is, I've got some logic inside my spider, where I'd like to create different WARC files and until they reach a certain size, need to stay in memory before being written to the disc.

I believe, I've almost got it working, but I can't figure out, how to build up the payload.
That's what I currently have:

    def write_response_to_memory(self, response):
        '''Writes a `response` object from Scrapy as a Warc record. '''
        response_url = w3lib.url.safe_download_url(response.url)

        # Create the payload string
        payload_temp = io.StringIO()

        for h_name in response.headers:
            payload_temp.write('%s: %s\n' % (h_name, response.headers[h_name]))
        
        payload_temp.write('\r\n')
        payload_temp.write(response.text)

        headers = []
        headers.append(tuple(('WARC-Type', 'response')))
        headers.append(tuple(('WARC-Date', self.now_iso_format())))
        headers.append(tuple(('Content-Length', str(payload_temp.tell()))))
        headers.append(tuple(('Content-Type', str(response.headers.get('Content-Type', '')))))

        http_headers_temp = StatusAndHeaders('200 OK', headers, protocol='HTTP/1.0')
        
        record = self.warcdict['test'].create_warc_record(response_url, 'response',
                                    payload=payload_temp.getvalue(),
                                    http_headers=http_headers_temp)

Which results into:

  File "/home/hpn/TestScripts/warc/scrapywarc/scrapywarc/spiders/scrapywarc.py", line 123, in write_response_to_memory
    http_headers=http_headers_temp)
  File "/home/hpn/live/ccd/lib/python3.7/site-packages/warcio/recordbuilder.py", line 117, in create_warc_record
    self.ensure_digest(record, block=False, payload=True)
  File "/home/hpn/live/ccd/lib/python3.7/site-packages/warcio/recordbuilder.py", line 191, in ensure_digest
    for buf in self._iter_stream(record.raw_stream):
  File "/home/hpn/live/ccd/lib/python3.7/site-packages/warcio/recordbuilder.py", line 218, in _iter_stream
    buf = stream.read(BUFF_SIZE)
AttributeError: 'str' object has no attribute 'read'

Is there any documentation of what the payload needs to look like?
Or is there an alternative way to add my content and header to create_warc_record?

**Comment by wumpus** [comment]
This code has multiple bugs.

You're passing a str for the payload= argument, that's the reason for the crash. io.BytesIO is an example of an object that will work.

The payload should just be the http payload, not headers and payload.

For a fully worked out example of writing a warc in a crawler, see https://github.com/cocrawler/cocrawler/blob/master/cocrawler/warc.py

**Comment by Chris8080** [comment]
Thanks for the hint.

This one is working now and if I read the files with the ArchiveIterator, it shows values correctly.
Could you take a glimpse and see whether there are any obvious flaws?
I'll try to make the code a bit nicer as well.

    def write_response_to_memory(self, response):
        '''Writes a `response` object from Scrapy as a Warc record. '''
        response_url = w3lib.url.safe_download_url(response.url)
        
        # Create the payload string
        resp = response.text.encode('utf-8')

        self.warcdict['testsize'] += sys.getsizeof(resp)
        
        # Create the header information list
        headers = []
        headers.append(tuple(('WARC-Type', 'response')))
        headers.append(tuple(('WARC-Date', self.now_iso_format())))
        headers.append(tuple(('Content-Length', str(len(resp)))))
        headers.append(tuple(('Content-Type', str(response.headers.get('Content-Type', '')))))

        self.warcdict['testsize'] += sys.getsizeof(headers)
        
        http_headers_temp = StatusAndHeaders('200 OK', headers, protocol='HTTP/1.0')
        
        record = self.warcdict['test'].create_warc_record(response_url, 'response',
                                    payload=BytesIO( resp ),
                                    http_headers=http_headers_temp)
        try:
            self.warcdict['test'].write_record(record)
            self.record_amount += 1
        except:
            pass
            
        warcmb = int ( self.warcdict['testsize'] ) / 1024 / 1024
        
        if warcmb >= 5:
            self.f.write(self.warcdict['test'].get_contents())
            self.f.close()

**Comment by wumpus** [comment]
It looks ok if your purpose is just scraping and not archiving. If you want to archive, you'll want to save the actual response headers.

As a minor point, if the response doesn't have a Content-Type header, you probably don't want to create an empty one in the warc.

**Comment by Chris8080** [comment]
I've added all headers and set the content type in case it's empty. 
The program is more about scraping / storing the HTML only - but it might be good to have the header info in place.
Thank you for your support.
