### ISSUE TITLE
Jinja2 started using f-strings & stopped being installable in Python 2.7

### ISSUE THREAD

**Issue by wumpus** [webrecorder/warcio#103]
I tried to set up travis to test my develop-warcio-test branch, see https://travis-ci.org/wumpus/warcio

Jinja2 3.0.0a1 uses f-strings. This repo's travis config tests Python 3.4/3.5 which do not support f-strings. You can pin an earlier version.

Python 2.7 installing Jinja2 in setuptools, that's a similar issue.

**Comment by wumpus** [comment]
https://github.com/pallets/jinja/issues/1154

The guy replying to this issue seems to think that this pre-release Jinja2 version is properly marked in its metadata. We're getting it via httpbin==0.5.0

**Comment by wumpus** [comment]
They appear to think we should only use `pip` and `tox` for installation and test.

**Comment by ikreymer** [comment]
Thanks for finding this.. Looks like this will be a more general probably for pywb also.. Yeah, probably should stop using `python setup.py test`

**Comment by wumpus** [comment]
Also we probably need to move to requirements.txt and pip install, as opposed to the current .travis.yml use of "python setup.py install" ... it wasn't test that caused the failure, it was travis and the install.

**Comment by ikreymer** [comment]
Hm, well travis tests seem to be passing with change referenced above:
https://travis-ci.org/webrecorder/warcio/builds/652835115

**Comment by ikreymer** [comment]
Fixed in the travis build. Since py27 now no longer supported, probably should spend more time on this.
Released with 1.7.2
