### ISSUE TITLE
ArchiveIterator is adding bytes to payload HTTP header without updating Content-length

### ISSUE THREAD

**Issue by lpla** [webrecorder/warcio#104]
Using ArchiveIterator to filter some WARC records, I noticed that it adds some bytes to the HTTP header without updating the Content-length (`record.length`) in memory. Given this code:
```
with open(warcfilebasename + ".warc", 'rb') as f_in:
        with open(warcfilebasename + ".warc.gz", 'wb') as f_out:
            writer = WARCWriter(f_out, gzip=True)
            try:
                for record in ArchiveIterator(f_in):
                    if record.http_headers:
                        if record.http_headers.get_header('Transfer-Encoding') == "chunked":
                            continue
                        try:
                            record.http_headers.to_ascii_bytes()
                        except UnicodeEncodeError:
                            # if header is non ascii, create a new header, with status code only
                            # content length and content type will be filled before writing
                            record.http_headers = StatusAndHeaders(record.http_headers.get_statuscode(), [])
                    writer.write_record(record)
            except:
                pass

```

and this input WARC generated by `wget`: 
[awt.zip](https://github.com/webrecorder/warcio/files/4213392/awt.zip)

It generates this WARC with wrong Content-length in the record 'urn:uuid:47ef9267-a4cc-47fa-a1b2-ddc6e746216d': 
[awt.warc.gz](https://github.com/webrecorder/warcio/files/4213393/awt.warc.gz)

This WARC crashes using `warcio index awt.warc.gz`, the previous one doesn't.

If I add `record.length = None` before `writer.write_record(record)` to my code, warcio recalculates the increased WARC content length before writing the output and then it works with `warcio index`.

The issue is, why does ArchiveIterator add content to the HTTP header when reading? And if that is necessary, why doesn't it update the content length?

Is this related to #57 ?

**Comment by ikreymer** [comment]
Looks like this is related to to the Content-Disposition re-encoding that warcio is doing...

But what is it that you're trying to do.. remove the non-ascii headers altogether?
I believe `to_ascii_bytes()` already catches encoding errors, so that should not throw.

The issue you have can actually just be reproed with just:

```
with open(warcfilebasename + ".warc", 'rb') as f_in:
        with open(warcfilebasename + ".warc.gz", 'wb') as f_out:
            writer = WARCWriter(f_out, gzip=True)
            for record in ArchiveIterator(f_in):
                writer.write_record(record)
```

The issue happens because:
```
Content-Disposition: attachment; filename="BIZKAIKO-AIZKORA-TXAPELKETA-2ª-eus.pdf";
```

is rewritten to:

```
Content-Disposition: attachment; filename*=UTF-8''BIZKAIKO-AIZKORA-TXAPELKETA-2%C2%AA-eus.pdf;
```
automatically, but for some reason the size is not adjusted. Will look for a fix.

**Comment by ikreymer** [comment]
Now fixed on develop, thanks!

**Comment by ikreymer** [comment]
and deployed in 1.7.2
