### ISSUE TITLE
Option to read the optional headers (languages-cld2, fetchTimeMs, charset-detected)

### ISSUE THREAD

**Issue by thomas0sae** [webrecorder/warcio#109]
There seems to be no way of reading the optional headers that appears between the metadata and request headers. 
 
fetchTimeMs: 1313
charset-detected: UTF-8
languages-cld2: {"reliable":true,"text-bytes":29834,"languages":[{"code":"de","code-iso-639-3":"deu","text-covered":0.99,"score":990.0,"name":"GERMAN"}]}

From CC-MAIN-20200216182139-20200216212139-00000.warc.gz

**Comment by wumpus** [comment]
These are metadata records, here's how to print their content. They are different from the request record, which has the request headers as the content of the record.

```
import sys
from warcio.archiveiterator import ArchiveIterator

with open(sys.argv[1], 'rb') as stream:
    for record in ArchiveIterator(stream):
        if record.rec_type == 'metadata':
            print(record.content_stream().read())
```

Example output

```
b'fetchTimeMs: 1591\r\ncharset-detected: GB2312\r\nlanguages-cld2: {"reliable":true,"text-bytes":3887,"languages":[{"code":"zh","code-iso-639-3":"zho","text-covered":0.95,"score":1986.0,"name":"Chinese"}]}\r\n\r\n'
```
