### ISSUE TITLE
Migrate CI

### ISSUE THREAD

**Issue by wumpus** [webrecorder/warcio#120]
travis-ci has basically ended free builds for open source projects.

Migrate our CI to something that's still free:

  [GitHub actions](https://github.com/features/actions)
  [Azure PIpelines](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-more-build-vs?view=azure-devops)
  [appveyor free tier](https://www.appveyor.com/pricing/) -- we have a working Windows config already
  GitLab -- free CI for qualifying OSS projects, else 400 minutes/month

One possibility is to use a tool that is compatible with multiple CI services:

  [mkdkr](https://github.com/rosineygp/mkdkr)

@ikreymer I have not migrated my pile of OSS projects yet so I can't give good advice

**Comment by wumpus** [comment]
I switched all of my projects over to Azure Pipelines, for no particular reason.

Our travis-ci setup uses codecov, and [here is a blog entry about using it with azure pipelines](https://devblogs.microsoft.com/devops/uploading-to-codecov-just-got-easier/)

While we're in there we should change setup.py to not do testing, that's deprecated.

**Comment by ikreymer** [comment]
Webrecorder now has a limited amount of Travis credits, but I think we'll need them for the cross-platform builds to support old versions of OSX.
I've used github actions and its been pretty smooth so far, so I think would lean towards just setting that up, lest have too many different configs.
What are the main advantages of azure pipelines?

**Comment by wumpus** [comment]
I don't see any advantage of azure pipelines over github actions, I just happen to have tried Azure first.

Azure has macOS-10.14 and macOS-10.15, btw, and those mix-and-match with a variety of python versions. I suppose the details of what's available does vary across these various services.

**Comment by tw4l** [comment]
Currently migrating the CI from Travis to GitHub Actions, which involves:

- [x] Updating Python versions to supported versions in test OS (Python 3.7-3.11)
- [x] Upgrading httpbin to PSF-supported >=0.10.2
- [x] Modify cache to file test to avoid wsgiref bug with returning bytestring from httpbin's `/bytes/<int>` endpoint ( see https://github.com/python/cpython/issues/110001)
- [ ] Modify proxy tests to account for `localhost:port` no longer being supported a valid proxy in requests/Python 3.9+ (see https://github.com/psf/requests/issues/6032; in progress)

**Comment by tw4l** [comment]
I've left a comment in an existing requests issue about this: https://github.com/psf/requests/issues/6015#issuecomment-2130362556

Hopefully it'll get picked up, in the meantime I might try using a different library for these tests.
