### ISSUE TITLE
How to retrieve the record based on target-uri?

### ISSUE THREAD

**Issue by kartheek7895** [webrecorder/warcio#32]
How to retrieve the record based on target-uri once indexes are created on the warc file?

**Comment by wumpus** [comment]
https://stackoverflow.com/questions/49377839/retrieving-records-from-warc-file-based-on-url/49378740

**Comment by kartheek7895** [comment]
How do I get the offset of each record,  as I'm doing f.tell() while iterating, however, when I tried to extract the record based on that offset, I'm not able to retrieve the record? Upon inspection, there is a difference between my offset() and offset generated by warcio index. Can someone throw some light on how warcio index is creating the offset?
