### ISSUE TITLE
is 'latin-1' charset for warcinfo payload correct?

### ISSUE THREAD

**Issue by wumpus** [webrecorder/warcio#6]
warcwriter:create_warcinfo_record does this to the payload lines:

            warcinfo.write(line.encode('latin-1'))

Is that correct? I looked through the 1.0 draft standard and it appears to say that utf8 can appear anywhere, and no mention of latin-1.

If latin-1 is correct, it needs errors='something' in case python3 users send in stuff that won't encode latin-1.

**Comment by ikreymer** [comment]
Hm, yeah, I think you're right, this is a mistake! This should be UTF-8 as its warcinfo contents and not warc or http headers.

**Comment by wumpus** [comment]
OK.

As for warc headers, they can have utf-8... which looks like that's done correctly already? But not tested.

And for http headers, https://tools.ietf.org/html/rfc5987 says there's a funky encoding to use if you want non-latin-1. I have no idea if useragents typically decode them or not. If they do, then someone's got to encode them before printing into the warc? The warc standard is silent about this issue?

**Comment by ikreymer** [comment]
Yeah, this is all very confusing unfortunately.. Currently, both WARC and HTTP headers are encoded as ISO-8859-1/Latin-1
https://github.com/webrecorder/warcio/blob/master/warcio/statusandheaders.py#L148

I think the HTTP headers should be whatever the original encoding was, which is probably ISO-8859-1. [https://www.python.org/dev/peps/pep-3333/#unicode-issues](PEP 3333) also assumes ISO-8859-1 for HTTP headers, so I think that is correct.

For WARC headers, it seems that it should be using UTF-8 as the default, based on this (slightly ambiguos wording):

`Although UTF-8 characters are allowed, the 'encoded-word' mechanism of [RFC2047] may also be used when writing WARC fields and shall also be understood by WARC reading software.
`

Heritrix seems to use UTF-8, while warcprox uses ISO-8859-1/Latin-1.

In conclusions, I think what we should have is:
- warcinfo contents as UTF-8
- WARC headers as UTF-8
- http headers as ISO-8859-1/Latin-1

**Comment by wumpus** [comment]
Yes, I agree with all that.

I'd like to eventually produce a small website and a corresponding .warc.gz which can be used as a 'torture test' for warc writers, readers, and playback. But that's an issue for another day.

**Comment by zuups** [comment]
Maybe my problem is connected with this issue? I'm getting errors with _warcio recompress_ of some arc/warc files (most files of the same crawl are ok but some are not)
`Traceback (most recent call last):
  File "/usr/local/bin/warcio", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/warcio/cli.py", line 47, in main
    cmd.func(cmd)
  File "/usr/local/lib/python3.4/dist-packages/warcio/cli.py", line 94, in __call__
    self.load_and_write(stream, cmd.output)
  File "/usr/local/lib/python3.4/dist-packages/warcio/cli.py", line 111, in load_and_write
    writer.write_record(record)
  File "/usr/local/lib/python3.4/dist-packages/warcio/warcwriter.py", line 347, in write_record
    self._write_warc_record(self.out, record)
  File "/usr/local/lib/python3.4/dist-packages/warcio/warcwriter.py", line 232, in _write_warc_record
    self._set_header_buff(record)
  File "/usr/local/lib/python3.4/dist-packages/warcio/warcwriter.py", line 224, in _set_header_buff
    headers_buff = record.http_headers.to_bytes(self.header_filter, 'iso-8859-1')
  File "/usr/local/lib/python3.4/dist-packages/warcio/statusandheaders.py", line 155, in to_bytes
    return self.to_str(filter_func).encode(encoding) + b'\r\n'
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 336-339: ordinal not in range(256)
`
Here are some files I have problems with: [http://veebiarhiiv.digar.ee/20180115warcencodeissue/](url)

**Comment by wumpus** [comment]
That's certainly utf-8 in an http header. https://tools.ietf.org/html/rfc5987 says that's not allowed, but we shouldn't be surprised that it happens.
