### ISSUE TITLE
configuring warc capture

### ISSUE THREAD

**Issue by johnknapp** [webrecorder/warcio#60]
I'm excited to adopt warcio in a project but I'm stuck.

Following the warcio warc write examples, **the warc files I create do not contain styles, images, fonts, videos.** However, the user experience on warcrecorder.io does contain those elements.

I'm not sure if I should be passing args, kwargs, params or a filter_function to achieve my desired result but examining the tests and source has left me without a clue!

I'd be very grateful if you could give me a hint or point me towards some samples.

**Comment by wumpus** [comment]
warcio isn't a browser and only captures exactly the url you asked for, not all of the stuff that a browser will access while displaying that url. You need to use much more complicated software like webrecorder.io if you want everything.

**Comment by johnknapp** [comment]
thanks Greg
