### ISSUE TITLE
AttributeError: 'brotli.Decompressor' object has no attribute 'unused_data'

### ISSUE THREAD

**Issue by sepastian** [webrecorder/warcio#73]
Hello, I'm using warcio to read a WARC archive containing brotli encoded HTTP responses like so.

```
with open(sys.argv[1],'rb') as stream:
    for record in ArchiveIterator(stream):
        if record.rec_type != 'response':
            continue
        print(record.content_stream().read())
```

This gives me the following error, because there is not attribute `unused_data` in `brotli`.

```
Traceback (most recent call last):
  File "load_warc.py", line 22, in <module>
    print(record.content_stream().read())
  File "/home/sebastian/.asdf/installs/python/3.7.2/lib/python3.7/site-packages/warcio/recordloader.py", line 34, in content_stream
    return ChunkedDataReader(self.raw_stream, decomp_type=encoding)
  File "/home/sebastian/.asdf/installs/python/3.7.2/lib/python3.7/site-packages/warcio/bufferedreaders.py", line 284, in __init__
    super(ChunkedDataReader, self).__init__(stream, **kwargs)
  File "/home/sebastian/.asdf/installs/python/3.7.2/lib/python3.7/site-packages/warcio/bufferedreaders.py", line 72, in __init__
    self._init_decomp(decomp_type)
  File "/home/sebastian/.asdf/installs/python/3.7.2/lib/python3.7/site-packages/warcio/bufferedreaders.py", line 89, in _init_decomp
    self.decompressor = self.DECOMPRESSORS[decomp_type.lower()]()
  File "/home/sebastian/.asdf/installs/python/3.7.2/lib/python3.7/site-packages/warcio/bufferedreaders.py", line 31, in brotli_decompressor
    decomp.unused_data = None
AttributeError: 'brotli.Decompressor' object has no attribute 'unused_data'
```

What am I missing?

**Comment by sepastian** [comment]
I'm using Google's official `brotli` package, is this correct?

I did

```
git clone https://github.com/google/brotli.git
cd brotli
git log -p | grep unused_data
grep -r unused_data
```

This doesn't give any results, so there is no `unused_data` in `brotli`, and there also has never been any. :thinking:

**Comment by ikreymer** [comment]
warcio uses the brotli-py library, installable with `pip install brotlipy`

I think it was available before the python bindings on the official google brotli..

Sorry for any confusion! Perhaps worth looking if it makes sense to switch..

**Comment by wumpus** [comment]
This is a doc problem, this project has no requirements.txt, setup.py doesn't mention brotli because it's optional, the only place the package name is mentioned is in .travis.yml and appveyor.yml

**Comment by ikreymer** [comment]
@wumpus you're right, probably a good solution would be toadd brotlipy as an `extras_require` and also mention in the README

**Comment by matteocargnelutti** [comment]
I think this is still an issue? I had to install brotlipy manually to be able to use `record.content_stream().read()` on `br` records. I think adding a little something in README would be a good first step :)

**Comment by ColeMurray** [comment]
This is still an issue, currently failing on this, resolved by ```pip install brotlipy```.

**Comment by wumpus** [comment]
fixed in PR https://github.com/webrecorder/warcio/pull/179, not sure when this will appear on pypi
